/* rmk-memory.x for for RP2040 2 MB — generated by rmk-boot
 *
 * Provides the MEMORY layout (absolute XIP addresses) and the standard
 * embassy-boot `__bootloader_*` partition symbols (flash-relative offsets)
 * consumed by init_flash_from_linkerscript().
 *
 * If your board has a different flash size, replace this file with the
 * matching file from the rmk-boot releases:
 *   https://github.com/rmk-rs/rmk-boot/releases
 */

MEMORY {
  FLASH : ORIGIN = 0x10007000, LENGTH = 1015808   /* ACTIVE region */
  RAM   : ORIGIN = 0x20000000, LENGTH = 256K                       /* SRAM */
}

/* Bootloader partition symbols — offsets relative to flash start.
 * The active/state/dfu names match embassy-boot's from_linkerfile_blocking(),
 * storage is an RMK extension.
 */
__bootloader_state_start   = 0x6000;
__bootloader_state_end     = 0x7000;
__bootloader_active_start  = 0x7000;
__bootloader_active_end    = 0xFF000;
__bootloader_dfu_start     = 0xFF000;
__bootloader_dfu_end       = 0x1F8000;
__bootloader_storage_start = 0x1F8000;
__bootloader_storage_end   = 0x200000;
